-- list the student_id numbers per each class
SELECT
    cls.class_id,
    cls.class_name,
    s.student_id
FROM
    yrkesco.class cls
JOIN
    yrkesco.student s ON cls.class_id = s.class_id
ORDER BY
    cls.class_id, s.student_id;

-- Check for Students Without Enrollment in Any Course
-- Ensure that no student is missing from any course enrollment, 
-- which might indicate a student without a course.

SELECT 
    s.student_id, 
    p.first_name, 
    p.last_name, 
    c.class_id, 
    c.class_name
FROM yrkesco.student s
JOIN yrkesco.person p ON s.person_id = p.person_id
LEFT JOIN yrkesco.class c ON s.class_id = c.class_id
WHERE s.student_id NOT IN (SELECT student_id FROM yrkesco.enrollment);
