SET 
    search_path TO ezecream_05;

-- cleans the table and resets the autogenerated pk value
TRUNCATE TABLE orders RESTART IDENTITY CASCADE;

INSERT INTO Orders (customer_id, order_date)
VALUES
    (2, '2024-05-04');


-- INSERT INTO ezecream_05.Orders (customer_id, order_date)
-- VALUES (5, '900-02-05');

SELECT * FROM ezecream_05.orders;

-- DELETE FROM ezecream_05.orders WHERE customer_id = 5;



    

