COPY ex2_ezecream.Customer 
FROM '/var/lib/postgresql/data/customer.csv' 
DELIMITER ',' CSV HEADER;

-- ELECT * FROM ex2_ezecream.customer;
-----------------------------------------------

COPY ex2_ezecream.Product 
FROM '/var/lib/postgresql/data/product.csv' 
DELIMITER ',' CSV HEADER;

-- SELECT * FROM ex2_ezecream.Product;
-----------------------------------------------

COPY ex2_ezecream.Orders 
FROM '/var/lib/postgresql/data/orders.csv' 
DELIMITER ',' CSV HEADER;

-- SELECT * FROM ex2_ezecream.orders;
-----------------------------------------------

COPY ex2_ezecream.Order_Detail 
FROM '/var/lib/postgresql/data/order_detail.csv' 
DELIMITER ',' CSV HEADER;

SELECT * FROM ex2_ezecream.Order_Detail;

